#!/usr/bin/env bash
#transfert file from local machine to server machine
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -gt 3 ]
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
else
    echo "it's 3"
fi
