#!/usr/bin/env bash
#setup web server with Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'y' | sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22/tcp
sudo ufw reload
sudo chown -R $USER:$USER /var/www/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
