#!/usr/bin/env bash
#setup web server with costum header
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'y' | sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22/tcp
sudo ufw reload
sudo chown -R "$USER":"$USER" /var/www/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.alxafrica.com permanent;/' /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "Ceci n'est pas une page" > /var/www/html/404_error.html
sudo sed -i 's/server_name _;/server_name _;\n\terror_page 404 \/404_error.html;/' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-enabled/default
sudo service nginx restart
