#!/usr/bin/env bash
#setup web server with Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
yes | sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22/tcp
sudo ufw reload
sudo su
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"
echo "$config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
