#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
#backend config
echo 'backend web_backend
        balance roundrobin
        server 430613-web-01 100.25.182.162 check
        server 430613-web-02 35.174.208.247 check
' >> /etc/haproxy/haproxy.cfg
#frontend config
echo 'frontend kacem-alx.tech
        bind 0:80
        mode http
        default_backend web_backend
' >> /etc/haproxy/haproxy.cfg
service haproxy restart
