#!/usr/bin/env bash
#backup and archive mysql databases
MYSQL_PASSWORD=$1
mysqldump -u root -p${MYSQL_PASSWORD} --all-databases > backup.sql
CURR_DATE=$(date +%d-%m-%Y)
tar -czvf ${CURR_DATE}.tar.gz backup.sql
