#!/usr/bin/env bash
#print 'Best School' 10 times with HI befor the last one
i=0
while [ $i -ne 10 ]
do
    if [[ $i -eq 9 ]]
    then
        echo "Hi"
        echo "Best School"
    else
        echo "Best School"
    fi
    i=$(( i + 1 ))
done