#!/usr/bin/env bash
#print 'Best School' with bad luck and good luck 
i=0
while [ $i -ne 10 ]
do
    if [[ $i -eq 3 ]]
    then
        echo "bad luck"
    elif [[ $i -eq 7 ]]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$(( i + 1 ))
done