#!/usr/bin/env bash
#script to update hosts file
cp /etc/hosts ~/hosts.new
sudo sed -i 's/.*localhost*./127.0.0.13   localhost/' ~/hosts.new
echo "8.8.8.8    facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts