#!/usr/bin/env bash
#config container so that nginx run as nginx user
sudo sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/^listen .*/listen 8080;/g' /etc/nginx/sites-available/default
sudo systemctl restart nginx
